languageCode = "zh-cn"
languageName = "中文"
weight = 1
title = "mkk Blog"

[params.author]
  name = "mkk"
  image = "https://kaikun.top/img/logoko.png"
  headline = "嵌入式开发工程师"
  bio = "嵌入式 | FreeRTOS | Linux | Python"
  links = [
    { github = "https://github.com/mkktop" },
    { email = "mailto:2864078813@qq.com" },
  ]
