# 主导航
[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "/posts"
  weight = 20

[[main]]
  name = "资源"
  pageRef = "/resources"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40

# 底部链接（友情链接）
[[footer]]
  name = "百度一下"
  url = "http://baidu.com"
  weight = 10

[[footer]]
  name = "我的B站"
  url = "https://space.bilibili.com/629233897?spm_id_from=333.1007.0.0"
  weight = 20

[[footer]]
  name = "我的图床"
  url = "https://image.kaikun.top"
  weight = 30
