colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/home-bg.jpg"
  showRecent = true
  showRecentItems = 8
  showMoreLink = false
  showReadingTime = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showSummary = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[verification]
  google = ""
